import { writable } from "svelte/store";

export const options = writable({
  composition: "source-over",
  count: 500,
  speed: 10,
  parallax: 1,
  direction: 180,
  xVariance: 2,
  yVariance: 2,
  rotate: true,
  rotation: 1,
  alphaSpeed: 10,
  alphaVariance: 1,
  minAlpha: 0,
  maxAlpha: 1,
  minSize: 1,
  maxSize: 10,
  style: "fill",
  bounce: false,
  drift: 1,
  glow: 0,
  twinkle: false,
  spawnFromCenter: false,
  spawnArea: 0,
  staggerSpawn: 0,
  /** @type {number[][]} [x, y] as % of canvas width/height (0–100); Sparticles default [[50, 50]] */
  spawnLocations: [[50, 50]],
  color: ["random"],
  shape: "circle",
  imageUrl: "",
});
