import { readable } from 'svelte/store';

export const presets = readable({
  default: {
    composition: "source-over",
    count: 500,
    speed: 10,
    parallax: 1,
    direction: 180,
    xVariance: 2,
    yVariance: 2,
    rotate: true,
    rotation: 1,
    alphaSpeed: 10,
    alphaVariance: 1,
    minAlpha: 0,
    maxAlpha: 1,
    minSize: 1,
    maxSize: 10,
    style: "fill",
    bounce: false,
    drift: 1,
    glow: 0,
    twinkle: false,
    color: ["random"],
    shape: "circle",
    imageUrl: "https://image.flaticon.com/icons/svg/692/692052.svg"
  },
  snow: {
    composition: "source-over",
    count: 160,
    speed: 5,
    parallax: 20,
    direction: 160,
    xVariance: 5,
    yVariance: 0,
    rotate: false,
    rotation: 0,
    alphaSpeed: 2,
    alphaVariance: 2,
    minAlpha: -1,
    maxAlpha: 1,
    minSize: 1,
    maxSize: 8,
    style: "fill",
    bounce: false,
    drift: 4,
    glow: 0,
    twinkle: false,
    color: ["white", "#e2e2e2"],
    shape: "circle",
    imageUrl: ""
  },
  sparkles: {
    composition: "source-over",
    count: 200,
    speed: 0,
    parallax: 0,
    direction: 180,
    xVariance: 0,
    yVariance: 4,
    rotate: false,
    rotation: 0,
    alphaSpeed: 4,
    alphaVariance: 10,
    minAlpha: -1,
    maxAlpha: 1,
    minSize: 2,
    maxSize: 10,
    style: "fill",
    bounce: false,
    drift: 0,
    glow: 0,
    twinkle: true,
    color: ["#f4bf5b", "#cad9df"],
    shape: "diamond",
    imageUrl: ""
  }
});
